version: '3'

volumes:
  postgres:
  redis:

services:
  db:
    image: kartoza/postgis
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
  redis:
    image: redis
    command: redis-server
    volumes:
      - redis:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    entrypoint: ["./entrypoint_api.sh"]
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    volumes:
      - .:/var/app/current
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/1
      RAILS_LOG_TO_STDOUT: 'true'
