redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: starter_cable

development:
  <<: *redis

test:
  adapter: test

staging:
  <<: *redis

production:
  <<: *redis